name: electricity-map
channels:
  - conda-forge
dependencies:
  - pip
  - arrow
  - pandas
  - ipyleaflet
  - ipyflex
  - ipywidgets
  - bqplot
  - voila
  - voila-material
  - geopy
  - requests 
  - pip:
      - aioelectricitymaps
      
  
